### ISSUE TITLE
XML for Home Activity: 

### ISSUE THREAD

**Issue by AgPriyanshu18** [bsoc-bitbyte/busify-android#2]
Create the XML layout for Home Activity, take reference form frame 2 of [Figma](https://www.figma.com/file/Kjmx7bRYRvUiwUPY2CCpW2/busifyAndroid?type=design&node-id=0-1&t=Pnc9yf0QOGCtIEdo-0).

Points to consider:
1. Use Constraint Layout (Make sure the layout is responsive to other screen sizes).
2. Do not make RecyclerView time layout for this issue, just add a RecyclerView there.

**Comment by adityakgupta** [comment]
@PraneGIT @AgPriyanshu18 I'd would like to work on this issue. Since it's already mentioned that we just have to add the RecyclerView, it will be very easy to recreate the figma design. I would like to suggest using a custom font for the project such as Roboto, Nunito or Montsterrat, is it possible to add these or we are supposed to use default font

**Comment by aarav0012** [comment]
@AgPriyanshu18 @PraneGIT I'm willing to work on this issue. I will create it as the figma design provided and make it as responsive as possible . could you please allow me to work on it

**Comment by PraneGIT** [comment]
@aarav0012 you can work on this
