### ISSUE TITLE
XML for recycler view items

### ISSUE THREAD

**Issue by PraneGIT** [bsoc-bitbyte/busify-android#3]
Create a XML layout for recycler view items for available slots in the [home activity](https://www.figma.com/file/Kjmx7bRYRvUiwUPY2CCpW2/busifyAndroid?type=design&node-id=0-1&t=tbTtmCJZTa0KNzop-0).

### Describe the solution you'd like

Points to consider:
1.Use constraint layout.
2.Make sure to wrap all  views in the item.

**Comment by adityakgupta** [comment]
@PraneGIT @AgPriyanshu18 I would like to work on this issue. From the designs it is clear that we have to use LinearLayoutManager, I will focus on keeping the color scheme and the design of the app to be as close to the figma designs as possible. I'd also like to work on adding custom animations instead of using the DefaultItemAnimator of RecyclerView.

**Comment by PraneGIT** [comment]
@Adi8712 go for it,and no need for any kotlin code we just need the xml for now for the item
